name: CI
on:
  push:
    branches:
      - master
  pull_request: null
jobs:
  zig:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - name: Build
        run: zig build
      - name: Run Tests
        run: zig build test --summary all
